### PR TITLE
Added location information and funny language :)

### PR DESCRIPTION
**Pull request by rubymorillo**
PLEASE ACCEPT THIS IS 100% ACCURATE!!!!!

### CODE REVIEW

**Comment by ajpiano** [comment]
This is truly hilarious. I had to ride a horse to get here.

**Comment by scottgonzalez** [comment]
THANKS SO MUCH!

**Comment by sfrisk** [comment]
This is the best.

**Comment by scottgonzalez** [comment]
do.co is down :-(

**Comment by rubymorillo** [comment]
GAAAAAHHHHHH

@scottgonzalez it's digitalocean.com, I used the shortener out of laziness =P

**Pull request merged**
