### PR TITLE
Closes #2 typo

### LINKED ISSUE #2: typo in readme
Boostrap isn't a thing :wink:

screenshot 2015-10-17 at 6 39 56 am

### PR DESCRIPTION
**Pull request by aperala**

### CODE REVIEW

**Comment by tcr** [comment]
:+1: for spooky boostrap :ghost: :skull:

**Comment by gnarf** [comment]
There are merge conflicts - can you update the branch?

**Comment by gnarf** [comment]
I'm totally :+1: on the change tho. 👍

**Comment by ashleygwilliams** [comment]
hey! it may be easier for you to just open a new PR given the merge conflicts. feel free to open a new one, mention this PR, and then merge it :)

**Comment by aperala** [comment]
Got it. Thanks for your help!

**Pull request closed without merging**
