### PR TITLE
Add Contributing instructions.

### LINKED ISSUE #18: Add a CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by gnarf**
Should Fix #18

### CODE REVIEW

**Comment by gnarf** [comment]
I'd like to get this in in it's earliest form, please save "add this" suggestions for pull requests, only block this from landing if you have problems with the content.  Thanks!

**Comment by kborchers** [comment]
:+1: for merging as initial version :heart:

**Comment by tcr** [comment]
:+1: wonderful

**Comment by Frijol** [comment]
looks good to me!

**Comment by tcr** [comment]
@gnarf Can you resolve the merge conflicts in this file?

**Comment by gnarf** [comment]
Rebased on current master - merging

**Pull request merged**
